# 情感分析项目配置文件
# 使用 YAML 格式，支持注释和更好的可读性

# 数据相关配置
data:
  data_path: "ChnSentiCorp_htl_all.csv"           # 原始数据文件路径
  processed_data_dir: "data/processed"            # 处理后数据保存目录
  test_size: 0.2                                  # 测试集比例
  val_size: 0.1                                   # 验证集比例
  random_state: 42                                # 随机种子
  max_length: 512                                 # 文本最大长度
  batch_size: 16                                  # 批处理大小
  num_workers: 2                                  # 数据加载器工作进程数

# 模型相关配置  
model:
  model_name: "bert-base-chinese"                 # 预训练模型名称
  model_type: "improved"                          # 模型类型: 'base' 或 'improved'
  num_classes: 2                                  # 分类类别数
  dropout_rate: 0.3                               # Dropout比例
  hidden_size: 768                                # 隐藏层大小
  use_contrastive_loss: true                      # 是否使用对比学习损失
  contrastive_weight: 0.1                         # 对比学习损失权重

# 训练相关配置
training:
  learning_rate: 2.0e-5                           # 学习率
  bert_learning_rate: 1.0e-5                      # BERT层学习率（通常更小）
  weight_decay: 0.01                              # 权重衰减
  max_epochs: 10                                  # 最大训练轮数
  patience: 3                                     # 早停耐心值
  gradient_clip_norm: 1.0                         # 梯度裁剪阈值
  warmup_steps: 0                                 # 学习率预热步数
  scheduler_type: "cosine"                        # 学习率调度器类型
  save_steps: 500                                 # 模型保存步数间隔
  eval_steps: 100                                 # 评估步数间隔
  logging_steps: 50                               # 日志记录步数间隔

# 系统相关配置
system:
  device: "auto"                                  # 设备选择: 'auto', 'cuda', 'cpu'
  mixed_precision: false                          # 是否使用混合精度训练
  dataloader_num_workers: 2                       # 数据加载器工作线程数
  pin_memory: true                                # 是否固定内存
  seed: 42                                        # 全局随机种子
  deterministic: true                             # 是否使用确定性算法
  
  # GPU内存管理
  gpu_memory_threshold: 0.9                       # GPU内存使用率阈值
  clear_cache_frequency: 50                       # GPU缓存清理频率（每N个batch）
  
  # 日志配置
  log_level: "INFO"                               # 日志级别
  log_file: null                                  # 日志文件路径（null表示不保存文件）
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # 日志格式

# 路径相关配置
paths:
  project_root: "."                               # 项目根目录
  data_dir: "data"                                # 数据目录
  model_dir: "models"                             # 模型目录
  output_dir: "results"                           # 输出结果目录
  log_dir: "logs"                                 # 日志目录
  checkpoint_dir: "models/saved_models"           # 模型检查点目录